// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/x1unix/go-playground/internal/builder (interfaces: CommandRunner)
//
// Generated by this command:
//
//	mockgen -destination=mock_runner.go -package=builder github.com/x1unix/go-playground/internal/builder CommandRunner
//

// Package builder is a generated GoMock package.
package builder

import (
	exec "os/exec"

	gomock "go.uber.org/mock/gomock"
)

// MockCommandRunner is a mock of CommandRunner interface.
type MockCommandRunner struct {
	ctrl     *gomock.Controller
	recorder *MockCommandRunnerMockRecorder
}

// MockCommandRunnerMockRecorder is the mock recorder for MockCommandRunner.
type MockCommandRunnerMockRecorder struct {
	mock *MockCommandRunner
}

// NewMockCommandRunner creates a new mock instance.
func NewMockCommandRunner(ctrl *gomock.Controller) *MockCommandRunner {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandRunner) EXPECT() *MockCommandRunnerMockRecorder {
	_ = "STUB: not implemented"

	// RunCommand mocks base method.
	return nil
}

func (m *MockCommandRunner) RunCommand(arg0 *exec.Cmd) error { _ = "STUB: not implemented"; return nil }

// RunCommand indicates an expected call of RunCommand.
func (mr *MockCommandRunnerMockRecorder) RunCommand(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
